---

- name: Install dep
  apt:
    name:
      - influxdb  # for Grafana
      # - python-geopandas  # for Grafana
      - apt-transport-https  # for Grafana
      - software-properties-common  # for Grafana
      - build-essential
      - libffi-dev
      - python3-dev
      - python3-pip
      - silversearcher-ag  # just for dev
      - rsync  # for ansible
      - python3-pandas
      - python3-numpy
    update_cache: yes
  become: true

- name: Install required pip programs
  pip:
    executable: pip3
    extra_args: --user
    name:
      - aiohttp[speedups]
      - aioinflux
      - pyserial-asyncio

- name: Create server directory
  file:
    path: /opt/server/
    state: directory
    owner: hoel
    mode: 0700
  become: true

- name: Sync server files
  synchronize:
    src: '~/git/Home_server/server/'
    dest: '/opt/server'
    rsync_opts:
      - "--exclude=*.pyc"
    checksum: true  # not needed but logic
  notify:
    - Restart server

- name: Create systemd service
  template:
    src: etc/systemd/system/server.service
    dest: /etc/systemd/system/server.service
  become: true
  tags: [conf]
  notify:
    - Reload systemd files
    - Restart server

- name: Enable and start server
  service:
    name: server
    enabled: true
    state: started
  become: true

- name: Check server API
  uri:
    url: 'http://{{ inventory_hostname }}:6000/'
    status_code: [200]
  register: result
  until: result.status == 200
  retries: 10
  delay: 2


# Grafana
# wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
# echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
# sudo apt-get update
# sudo apt-get install grafana
# sudo systemctl daemon-reload
# sudo systemctl enable grafana-server.service
# sudo systemctl start grafana-server
# Creer la DB sensors dans influxdb, voir le code Python

# Flash arduino from the board:
# python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
# sudo apt install python3-libgpiod
# sudo usermod -a -G gpio hoel
# mv /home/hoel/.platformio/packages/tool-avrdude/avrdude /home/hoel/.platformio/packages/tool-avrdude/avrdude_save
# ln -s /opt/server/avrdude-autoreset /home/hoel/.platformio/packages/tool-avrdude/avrdude
#
# To flash use:
# sudo systemctl stop server && \
# /home/hoel/.platformio/penv/bin/platformio run -d ~/nRF24_hub --target upload --upload-port /dev/ttyAMA0 && \
# sudo systemctl start server
